### ISSUE TITLE
Investigate pytest failures (MacOS)

### ISSUE THREAD

**Issue by doulikecookiedough** [DataONEorg/hashstore#27]
In the PR for [HashStore-beta](https://github.com/DataONEorg/hashstore/pull/25), we encountered test failures on Matt's machine (M1 MacOS). However, we are unable to reproduce these errors in GHA or Dou's machine (M2 MacOS). After comparing environments (`poetry show` and `poetry debug info`), it appears that Dou's installation of python is different from Matt's in the local python version installed via brew:

**Matt:**
```
Poetry
Version: 1.2.2
Python:  3.9.16

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /Users/jones/.virtualenvs/hashfs
Executable:     /Users/jones/.virtualenvs/hashfs/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.16
Path:       /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
Executable: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9
```

**Dou:**
```
(hstoretest3) doumok@Dous-MacBook-Pro hashstore % poetry debug info

Poetry
Version: 1.4.2
Python:  3.11.3

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /Users/doumok/.virtualenvs/hstoretest3
Executable:     /Users/doumok/.virtualenvs/hstoretest3/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.16
Path:       /Users/doumok/.pyenv/versions/3.9.16
Executable: /Users/doumok/.pyenv/versions/3.9.16/bin/python3.9
```

Install Python 3.9.16 via brew, create a new venv that points to that bin and run the tests to see if it's possible to reproduce the errors

**Comment by doulikecookiedough** [comment]
At this time, I am still unable to reproduce the test failures. 
- I have tried creating a new venv that points specifically to a python installation via brew
    - `mkvirtualenv hstoretest4 --python=/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9`
- I have also set the poetry config parameter `virtualenvs.prefer-active-python` to true, which did not change the version listed under 'Poetry' in `poetry debug info` - but forces all poetry installations to use the active-python version
    - `poetry config --list` to get the full property list
    - Example command to change a config parameter `virtualenvs.prefer-active-python false`
- Reinstalling poetry `brew reinstall poetry` does not appear to have resolved the Python version either
    - `python -V` is showing `Python 3.9.4` but `poetry debug info` is showing `3.11.3`

I found this article relating to the issue above (https://github.com/python-poetry/poetry/issues/655) - but there doesn't appear to be a permanent fix. @mbjones Are you able to try installing a specific python version via pyenv and reproduce the issue?

**Comment by doulikecookiedough** [comment]
My .zshrc file for reference:
```
export PATH="$HOME/.pyenv/bin:$PATH"
export PATH="/usr/local/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

export WORKON_HOME=~/.virtualenvs
mkdir -p $WORKON_HOME
. ~/.pyenv/versions/3.9.4/bin/virtualenvwrapper.sh
```

**Comment by doulikecookiedough** [comment]
Pytests are passing as well on MacOS Intel (2019 16" Macbook Pro) with the `poetry debug info` below.
```
Poetry
Version: 1.4.1
Python:  3.9.0

Virtualenv
Python:         3.9.0
Implementation: CPython
Path:           /Users/doumok/.virtualenvs/hashfs
Executable:     /Users/doumok/.virtualenvs/hashfs/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.9.0
Path:       /Users/doumok/.pyenv/versions/3.9.0
Executable: /Users/doumok/.pyenv/versions/3.9.0/bin/python3.9
```

Note - Python 3.9.16 is not on the available list of versions to install on this machine (`pyenv install --list`). Will continue to look into this inbetween tasks.

**Comment by doulikecookiedough** [comment]
**Additional Notes:**
- Reinstalled poetry based on their documentation recommendation (not encouraged through homebrew, uninstalled here)
    - Installation command: `curl -sSL https://install.python-poetry.org | python3 -`
    - Must add `export PATH="$HOME/.local/bin:$PATH"` to `.zshrc` in order for Poetry to be found (`poetry -V`)
- The python version underneath Poetry Version is based on the default python3 command (python3 - `which python`) - so I aliased python3 to the installation for 3.9.16 which is what produced the desired version underneath `Poetry/Version` in `poetry debug info`

**Comment by doulikecookiedough** [comment]
@mbjones - I ran into an issue yesterday when trying to add 'pyyaml' as a dependency to the project, which I would like to test to see if it can help with our pytest failures on your machine.

**Short (please read):**
-  When you have scope, can you please try manually changing your python interpreter in VSCode to a new venv or an existing venv and see if the tests are still failing? Below for quick reference:
```Shift + Cmd + P
-> "Python: Select Interpreter"
-> Enter interpreter path
-> "~/.virtualenvs/hashstore/bin/python"
```

**Context (optional):**
- I added the line pyyaml = "^6.0" manually to my pyproject.toml and ran poetry install but kept getting the error:
   -```Because hashstore depends on pyyaml (^6.0) which doesn't match any versions, version solving failed.```
- pyyaml is a valid package, and a few searches later... I realized I should instead add it by running `poetry add pyyaml` and it succeeded (yes!) - but I was still getting a compilation error for the line import yaml.
- So I created a new venv hashstore and ran poetry install - but the module still wasn't found even though poetry installed the dependencies successfully. Reloaded VSCode, still didn't work.
- Turns out, I had to manually change my python interpreter in VSCode to the another venv (ex. hashstore ) in order to trigger the module to be recognized. Switching venvs via `workon` didn't seem to work, not sure why. Now the module import error is gone, and my previous venvs also work too.

**Comment by doulikecookiedough** [comment]
Since the errors you're experiencing relate to the python standard library `hashlib`... I am thinking that there may be a caching issue with VSCode and perhaps it is looking at the wrong place for `hashlib` (or at an installation that got corrupted somehow). Manually changing the Python Interpreter could potentially "reset" the pathing (not completely sure how it works under the hood), and then resolve the checksums not matching.

**Comment by mbjones** [comment]
@doulikecookiedough I pulled your branch, did a `poetry install` on a completely new `hashstore` venv, and I saw the same issues with VS Code not resolving the new `yaml` import, even though from the terminal I could import it fine from the venv.  Same behavior as you saw I think. As this type of thing is almost always because of the wrong venv, I tried manually switching it, but it kept wanting to switch back to  a `hashfs` venv. Looking in `.vscode/settings.json`, I saw that the hashfs venv was set as the default in the settings, which I took to be the likely culprit. After removing that setting line and selecting my interpreter from the correct `hashstore` venv, VS Code then saw the yaml import fine, and all tests passed. This was on linux. So, I pushed these changes along with some formatting and linting config changes to your branch in SHA 09e2626.

I am still having checksum comparison problems on Mac, but haven't had time to track those down. As the tests work fine on linux for me, I'm sure its a local config thing that I'll figure out eventually.

**Comment by mbjones** [comment]
Also added `@slow_test` annotation to the large file test, taking the test cycle time from 5 minutes to 5 seconds. You can run all tests with `pytest --run-slow`, but a normal `pytest` will skip the slow ones. See SHA 7f2f907b.

**Comment by mbjones** [comment]
Finally, one more note. You can massively speed up the test of the large file storage by creating a sparse file using `seek`, rather than your current approach of looping through and writing 1 to 4 Gb of random data to the file. From a checksum perspective, the file contents don't matter so much. When I create the temp file with this code starting on line https://github.com/DataONEorg/hashstore/blob/feature-29-hashstore-configuration/tests/filehashstore/test_filehashstore_interface.py#L428 :

```python
    with open(file_path, "wb") as file:
        file.seek(file_size - 1)
        file.write(b'\0')
```

Then the test drops from 5 minutes to about 42 seconds, which is the time it takes to calculate the checksum twice. I'm not sure if the checksum calculation is the faster as well, so it might not be as good of a test as on random data, but its still technically calculating the checksum across the larger file. Not sure if you want to make this change or not given the objectives of the test, so just leaving it here.

**Comment by doulikecookiedough** [comment]
**RE: Large File Tests**
- I would like to have both tests, but modify the large file test (with sparse file) to write a 4GB file instead of 1GB. I have annotated this new test with `@slow_test` as well.

It looks like it's safe for me to close this issue, thank you again for taking time to go over this and reviewing my branch! Please don't hesitate to re-open this issue and comment if there's anything else you would like me to review/look into.
